### ISSUE TITLE
Please remove redux-observable

### ISSUE THREAD

**Issue by steida** [flowtype/flow-typed#1020]
The current implementation doesn't help anything. 

https://github.com/flowtype/flow-typed/pull/1007#issuecomment-313544471

**Comment by GAntoine** [comment]
What do you mean by "doesn't help anything"? We'll need more detail about what's not working.

**Comment by Ailrun** [comment]
Current implementation requires solving [this issue](https://github.com/flowtype/flow-typed/issues/16).
I believe this issue will be solved, so I made redux-observable implmentation.

**Comment by Ailrun** [comment]
However, I don't agree with this issue because

1. If anyone want to implements lib def *working with rxjs*, he can extends my lib def with rxjs codes, i.e., copy-and-paste, like [this author](https://github.com/flowtype/flow-typed/pull/211) does on bitcoin-js with bigi and ecurve library. Therefore, I believe my lib def at least helps those who want to implement more *currently working* one.
2. When above issue is solved, my libdef will works.

**Comment by steida** [comment]
Thank you @Ailrun for your work. In this bloody world, I will have to manually delete that definition probably forever because I don't believe they will manage to fix it in next few years...

To not be only party pooper, here is how to use types with redux-observable meanwhile https://github.com/este/este/blob/5e9e4905762885ece7895b6ceed9678fa844a8c2/types/index.js#L122

**Comment by Ailrun** [comment]
@steida
If you really believe so, than you can extend it yourself!
If really they will not fix it for next few years (and you believe so), Adding loooong rxjs libdef to redux-observable libdef is not so painful, compared to manual install-delete or without any type related with redux-observable

**Comment by steida** [comment]
Let's see.
