### ISSUE TITLE
Styled-components 2 disabled

### ISSUE THREAD

**Issue by marudor** [flowtype/flow-typed#1110]
@mwalkerwells 
Could cou make a PR that fixes this?
I got a ton of errors and I'm not able to fix them real quick.

**Comment by mwalkerwells** [comment]
What do you mean by disabled?

**Comment by marudor** [comment]
I've commented it out. Making it unusable.

**Comment by mwalkerwells** [comment]
Ah, I see you commented the library definition out. What errors are you getting?

**Comment by marudor** [comment]
Several test related.
About Stuff not being a react Component

**Comment by oliverturner** [comment]
> I've commented it out. Making it unusable.
@marudor Doing so broke my app's flow set-up: your change causes flow to report that styled-components is a missing module.

Can you please roll back to the last known good release or at least replace it with a stub? Thank you.

**Comment by thejameskyle** [comment]
@oliverturner you should be committing your `flow-typed` directory, not installing fresh all the time.

**Comment by oliverturner** [comment]
Good point, but in this instance it was a legitimate fresh install

**Comment by marudor** [comment]
Removed now. I was hoping to get a fix for this real quick. Sadly I didn't.

**Comment by oliverturner** [comment]
@marudor no worries: thanks and sorry for pestering you on your weekend.

**Comment by mwalkerwells** [comment]
I have a fix in the works, but wasn't able to finish before heading out of
town. Sorry guys! I'll submit a PR tomorrow though.

On Aug 5, 2017 8:09 AM, "Oliver Turner" <notifications@github.com> wrote:

@marudor <https://github.com/marudor> no worries: thanks and sorry for
pestering you on your weekend.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/flowtype/flow-typed/issues/1110#issuecomment-320448914>,
or mute the thread

**Comment by mwalkerwells** [comment]
If you have any feedback, please let me know!
