### ISSUE TITLE
[express] express$Application missing typedef for get method

### ISSUE THREAD

**Issue by thiemok** [flowtype/flow-typed#1120]
express$Application is missing its typedef for the get method. Its commented out in the libdef.
See [express libdef](https://github.com/flowtype/flow-typed/blob/master/definitions/npm/express_v4.x.x/flow_v0.32.x-/express_v4.x.x.js) line 175. Is this an oversight or intentional?

**Comment by marudor** [comment]
The current Problem is that the get on express$Application is not compatible with the get on express$Router.
If we comment it back in it will fail on the checks for the routing.
So far there has been no good workaround. Thats why it is commented out.

**Comment by Baptiste-Garcin** [comment]
I feel it's very wrong but here is my workaround.

```
declare class express$Application extends net$Socket mixins events$EventEmitter {
  constructor(): void;
  locals: {[name: string]: mixed};
  mountpath: string;
  listen(port: number, hostname?: string, backlog?: number, callback?: (err?: ?Error) => mixed): Server;
  listen(port: number, hostname?: string, callback?: (err?: ?Error) => mixed): Server;
  listen(port: number, callback?: (err?: ?Error) => mixed): Server;
  listen(path: string, callback?: (err?: ?Error) => mixed): Server;
  listen(handle: Object, callback?: (err?: ?Error) => mixed): Server;
  disable(name: string): void;
  disabled(name: string): boolean;
  enable(name: string): express$Application;
  enabled(name: string): boolean;
  engine(name: string, callback: Function): void;
  use(middleware: express$Middleware): this;

  use(...middleware: Array<express$Middleware>): this;
  use(path: string|RegExp|string[], ...middleware: Array<express$Middleware>): this;
  use(path: string, router: express$Router): this;
 
  get(name: string, callback?: Function): mixed | void;

  set(name: string, value: mixed): mixed;
  render(name: string, optionsOrFunction: {[name: string]: mixed}, callback: express$RenderCallback): void;
  $call: (req: http$IncomingMessage, res: http$ServerResponse, next?: ?express$NextFunction) => void;
}
```

As you can see, I replace the express$router inheritance and I add all the 'use' case that originally were in the router class then I uncomment the get method.

You notice that I replace the inheritance by net$Socket. That's because my application type need a some point to access to the `address()` method that is in net$socket which is defined inside of node.

I also had to add the `$call: (req: http$IncomingMessage, res: http$ServerResponse, next?: ?express$NextFunction) => void;` that I copy/paste from the router class.

I am a rookie in web development and how flowtyped work is for me a mystery so before cursing my soul for what I have done, can you explain me why it is so bad ?

Thanks
