### ISSUE TITLE
Doesn't support '>=' in top-level directory

### ISSUE THREAD

**Issue by LegNeato** [flowtype/flow-typed#125]
From https://travis-ci.org/flowtype/flow-typed/builds/133284414

```sh
Found some problems with bull_>=v0.7.2:
  * 'bull_>=v0.7.2' is a malformed definitions/npm/ directory name! Expected the name to be formatted as <PKGNAME>_v<MAJOR>.<MINOR>.<PATCH>
```
The docs say:

_Where <VERSION> is a semver version number with all of MAJOR, MINOR, and PATCH version numbers included. x is an acceptable wildcard in place of any of the three version numbers, and it is also acceptable to put >= or <= in front of the v to indicate a range of versions._

`bull` has both `0.7.x` and a `1.0.x` releases...the interface is largely the same between the two. I'll bump up to 1.x.x to unblock myself, but this should probably be supported?

**Comment by ryyppy** [comment]
I think this issue is already solved, right?

**Comment by jeffmo** [comment]
No, we don't support `>=` because it gets tricky (really tricky) to do proper range matching -- but also because semver versions describe the API, and it's pretty rare that all future versions of a given library retain the exact same API.

I didn't notice the second half of this issue until now though -- where it't pointed out that the README suggests you can do this. We should probably fix the README.

**Comment by jeffmo** [comment]
I've updated the README to clarify this a bit. Thanks for reporting (and sorry for the delay in response!)

**Comment by jeffmo** [comment]
PS: For cases where the interface *really is* the same between two versions, it's probably best to just create a copy.
