### ISSUE TITLE
No possibility to test behavior with different modules?

### ISSUE THREAD

**Issue by apsavin** [flowtype/flow-typed#1331]
Sometimes `flow` works different in the following cases:

1. code in one file
2. code in different files

But it seems that we can't write tests right now that can check the second case.

I tried to fix `react-redux` libdefs. I need to declare a connected React component in one file and check its usage in another to reproduce a bug. I tried to create `TestComponent.js` file near `test_connect.js`, but checker says that I need to use name for file that starts with `test_`. But when I renamed a file to `test_component.js`, I got an error 
```
* react-redux_v5.x.x/flow_v0.54.x- (flow-v0.55.0): Unexpected Flow errors(2):
   Error: 2-test_connect.js:4
     4: import CC3 from './test_CC3';
                        ^^^^^^^^^^^^ ./test_CC3. Required module not found
```

Can we handle the situation somehow?
Can I help?

**Comment by cprodescu** [comment]
+1 on this.

@GAntoine do you have a strong opinion on how this should be implemented?
1. remove [name mangling of test files](https://github.com/flowtype/flow-typed/blob/master/cli/src/commands/runTests.js#L504) (may need to rename some files to ensure unique test names across a library): 
2. add support for `test_foo` as directory (and maintain structure inside it without name mangling)
3. add support for `setup_foo.js` as setup files (will need to be unique name within a library)

I think 1 is simplest to implement and maintains current folder structure clear. Would add a clear error message if there are basename clashes.

Also cc @villesau since you are working on https://github.com/flowtype/flow-typed/pull/1731

**Comment by LoganBarnett** [comment]
Is there a known benefit to why we mangle the filenames now? It seems like that's separate from actually finding the test files, so without more information it seems like removing the mangling is the best thing to do.

**Comment by AndrewSouthpaw** [comment]
Agreed, seems reasonable to me (lacking much context here though). @LoganBarnett and I ran into a similar bug with Ramda, so it's definitely the case that many libraries would benefit from support here.

I'm concerned about cluttering the main testing directories, though, and like the idea of having a `test_files` folder for extra files related to tests. As it is right now, it's super clear where the defs and tests live, and it'll get muddled with extra helper files.

**Comment by villesau** [comment]
I don't see why there should be any difference wether the code lives in the same file or imported from another, especially if the code is well typed. Instead of writing workaround here, what about opening a bug report in Flow? Though, if it would be an easy fix, it would probably already been fixed (which on the other hand doesn't make it any less of a bug).

**Comment by LoganBarnett** [comment]
@villesau based on @cprodescu's post earlier (see item 1), it looks like this is a workaround in `flow-typed` that we're asking be removed.

The general gist of the bug is when writing code like this test:

``` javascript
import { type A } from 'a'
import b from 'b'

// returns an A
const a: A = b.getA()
```

But the import on the first line fails in `flow-typed` because of how names get mangled. Ordinarily code like this works just fine in `flow` land, so I don't think opening a bug there will address this, if that makes sense.

**Comment by cprodescu** [comment]
I agree with both of you :)

@villesau I agree ideally flow should have the same behavior in-module vs across modules, opening a ticket on this makes sense (would also remove the need for `%checks`, etc).

In the mean-time, I believe it is not unreasonable for `flow-typed` to support multi-file tests, as @LoganBarnett suggests. One note, the name mangling workaround was introduced in `flow-typed` to support multi-level tests with clashing names (`foo-lib/test.js` and `foo-lib/flow-0.23.x/test.js`).

About my proposal, I'm suggesting 1 since it's the simplest thing from the limited context I have. @GAntoine and @AndrewSouthpaw definitely have more context.

**Comment by villesau** [comment]
@LoganBarnett That makes perfect sense! Though, like the original post states, there _is_ difference wether the code lives in same file or not. So basically your code example might behave differently if module a and b would live in the file you are using them, apparently Flow looses some type information. I've experienced this too while writing react-redux types and trying them out in larger codebase.

**Comment by LoganBarnett** [comment]
@cprodescu @villesau ah - I'm probably confused about something then. In this case it looks like we're trying to include support files as a means of reuse, and that doesn't work because of the name mangling. I'm personally tracking some tickets that involve how information can be lost across the file barrier, so I totally get that it's is a problem in Flow. Where I am confused about is how any of these file-barrier issues exist in our use case _here_. The context I've been working with here is that we're trying to include local files and `flow-typed`'s require/import mechanism is mangling those names as it happens, which breaks the import. Is there more going on here?

Thanks for assisting with clarity for me here!

@cprodescu Avoiding name collisions seems like a legit concern, but I think I'd rather see us version our files (`./some-component_v0.33.x.js`) and we just import that file by its full name. If we're feeling brave we can name the file without any kind of version information assuming it will work across all versions, and split it apart when the need arises. It sounds like everyone on the thread is in agreement with that (or at least ditching the mangling), so I'm just being verbose as to how we'd address the original concern of the mangling, I think.

**Comment by cprodescu** [comment]
Thank you @AndrewSouthpaw!

**Comment by AndrewSouthpaw** [comment]
Sure thing! We'll see how it goes, there's still a chance we'll need to revisit it some day, but hopefully this is a decent strategy to move us forward. Thanks for opening the issue.
