### ISSUE TITLE
Improve Ramda's `#values` definition.

### ISSUE THREAD

**Issue by AndrewSouthpaw** [flowtype/flow-typed#1534]
cc @LoganBarnett 

I'm working on improving `R.values`, which currently in flow only allows objects of the same value type.

```js
R.values(({ a: 1, b: 'foo' }: { a: number, b: string })) // boom
```

Based on the functionality, we should be returning an array of values with types equal to those of the object. The trouble with `$ElementType` is that it requires a key to be specified, otherwise it can't type check. As far as I can tell, there's no utility type that allows us to extract dynamically the types of an object. (This probably has to do with the inherent shortcomings of trying to type a dynamic language, see the discussion of `Object.values` with flow [here](https://github.com/facebook/flow/issues/2221)).

Returning `Array<mixed>` seems utterly useless, and in fact makes things worse since you can hardly do anything with a `mixed` type, and would be annoying to have to typecast as `Array<any>` every time.

AFAICT, the only reasonable solution right now is to return `Array<any>`, which makes me sad.

Does anyone see a better alternative?

**Comment by LoganBarnett** [comment]
Yeah for what I can see `$Keys<T>` gives you a union of all of the key names for a `T`. `$ElementType` has to work with that union. It's almost like we want a `Literal` type which we can constrain by `$Keys<T>` and then we can feed that to `$PropertyType`. I would hope that would Just Work because we've resolved what `$PropertyType` wants: A literal string. We just did it further up the chain somewhere.

Would that work here in the case of `R.values`? I'm not sure - I'm kind of thinking out loud here with other things we've been running into with trying to harden the types of known objects as we perform highly abstract transformations on them.

Let's pretend for a moment that we could have any utility type we wanted with our magic utility type creating wand. What would we do to express `values`? We could somehow convert all of the property/element types into a tuple, but order isn't guaranteed. You'd have to disambiguate every entry, _however_ you could probably do it with a constraint. This might be where `$ElementType` indeed shines. I would expect the best we could do is get a union of all types that the collective properties of the object uses.

Another thing I want to throw out there: Those of us using Flow have felt the impact it's had on our approach to Javascript. For example, my team is considering dropping `===` in favor of `==` because Flow can overcome Javascript's shortcomings with `==` and provide _much stricter typing_. I certainly can say I've written many `switch` statements due to the way Flow corrals means of disambiguations/refinements into just looking at the value of a single property. Is embracing `values` further than what `$ElementType` can provide us going to make us fighting Flow? I don't want this to be a hand wave of desire to have this as strict as possible (and we should do what we can). Just that perhaps this is kind of treatment might just be as good as we can get it.

Of course, after I've said all of this I'm sure someone will show some way in which you can express this soundly in some ML dialect without macros :P

**Comment by AndrewSouthpaw** [comment]
I like the idea about `$PropertyType` with a `Literal` type, but unfortunately it demands a string: see [here](https://flow.org/try/#0C4TwDgpgBAChBOBnA9gOygXigbwFBSlQEMBbCALikWHgEtUBzAGnyiIYsIFcSAjBFgTBF4EVMEpwkaXAF8A3LlwBjNNUIQA7gEEOlACQx4ySPFAAVcBAA8UlKiZQA5OwhOoAH2fEyTgHyYUACsAAyKQA).

I agree with you, a union of all types present in values would be the best we could do, and even that isn't all that useful.

**Comment by LoganBarnett** [comment]
I haven't checked no Typescript much.

I was thinking some kind of `$Literal<T>` would satisfy the second argument in `$PropertyType` because it would require that at some point `$Literal` would have to be some kind of literal string. You just didn't need to type it? It would mean Flow would have to defer resolution of the type until later. I want to say I think it can do that, but my understanding of the innerworkings of Flow is practically nonexistent.

The Flow team has a lot on their plates, but I'll make a feature request for it and link to here to give them an idea of our use case.

**Comment by LoganBarnett** [comment]
Well shucks.

It looks like they've recently updated the documentation. See the docs for [`$ElementType`](https://flow.org/en/docs/types/utilities/#toc-elementtype). Particularly they show it used with generics with an arbitrary `getProp` function. I know this still doesn't help with `values`, but perhaps we can strengthen some other of Ramda's functions now that we have a working example.

**Comment by AndrewSouthpaw** [comment]
Yeah, that's what led me to working on `values` in the first place. :) I've already done it for `prop` and `propOr`, and I think one or two others. I was planning to go over some others probably over the weekend.
