### ISSUE TITLE
[CLI] Support for .flowconfig root directory

### ISSUE THREAD

**Issue by jessicarobins** [flowtype/flow-typed#1760]
The flow cli allows you to specify the root directory, so we have our `.flowconfig` inside our `src/` directory. This made us unable to use the flow-typed cli though because our `node_modules/` directory isn't in `src/`. A `--root` argument on `flow-typed install` would be helpful, I think.

I'd be happy to make a PR for this if it'd be helpful for others too!

**Comment by sepo-one** [comment]
Up vote !

Forcing to place `.flowconfig` into root only is rude ).
Because by default flow will include all directories under `root`; including `.git` !, which could take a lot of unnecessary time for flow to parse.
To overcome this, i normally put `.flowconfig` into `src` folder and `[include]`  only stuff needed from the root.
But unfortunately `flow-typed` doesn't understand this, because `process.cwd()` is used :(
