### ISSUE TITLE
[aws-sdk] aws-sdk-flow-decls appear unmaintained, does flow-typed want working aws-sdk types?

### ISSUE THREAD

**Issue by awilkins** [flowtype/flow-typed#2104]
Yup, I know that `aws-flow-sdk-decls` is not part of this project but I was wondering if it would be something the flow-typed team would be interested in.

The published NPM module is somewhat old now and doesn't include all of the current APIs. The maintainer seems to have lost interest a couple of years ago.

[aws-sdk-flow-decl-gen](https://github.com/motiz88/aws-sdk-flow-decl-gen) still seems to work well and I have resorted to using it and plonking the result in the top level of my `flow-typed` source folder... although I suspect I'll end up forking it and aiming my package.json at my fork in gitlab soon.

Upsides : the AWS SDK has a mammoth and complex API and help with it is very welcome.

Downsides: the AWS SDK has a mammoth API (75klines of generated type declarations) and including these defs in your projects can make flow noticeably sluggish.

**Comment by motiz88** [comment]
I am the author of `aws-flow-sdk-decl-gen` and `aws-sdk-flow-decls`. My apologies for not being able to maintain them the last couple of years, happy to hear the generator still works though!

To be honest I am thinking of bringing the declarations up to date and maybe fully automating releases so that less maintenance is needed going forward. Also it's probably worth checking whether any new Flow features since the original release have made it possible to generate less code and hopefully improve performance.

@awilkins I'll open relevant issues on the repos soon to plan/track this work and you're more than welcome to participate - feedback from actual users is super valuable.

**Comment by awilkins** [comment]
Excellent!

I know at least one thing can get done - the issue linked at the top of the generated output is no longer an issue.

I've also patched some of the preamble a bit for e.g. missing update method in config class.

Would also love to see it generate separate typedefs for different bits of the AWS SDK but appreciate that Flow currently makes this a total PITA AFAIK. The whole set is monstrous and has a noticeable impact on Flow's performance (unless I have another issue).

:+1:

**Comment by AndrewSouthpaw** [comment]
Seems like this can be closed, LMK if that's not the case.

**Comment by taybin** [comment]
Can we reopen this?  `aws-flow-sdk-decls` still hasn't been updated since 2016, despite the author's participation in this issue.
