### ISSUE TITLE
Documentation pass

### ISSUE THREAD

**Issue by gabelevi** [flowtype/flow-typed#254]
There's already the [README.md](https://github.com/flowtype/flow-typed/blob/master/README.md) and [CONTRIBUTING.md](https://github.com/flowtype/flow-typed/blob/master/CONTRIBUTING.md) but we probably need more documentation, including some on flowtype.org

**Comment by avikchaudhuri** [comment]
What kind of documentation are we thinking of here? Just the process of creating / testing libs, or getting into the libs syntax / what do use when / naming conventions for globals / how to export what / other recommendations?

**Comment by avikchaudhuri** [comment]
Getting a list started after talking to @jeffmo offline:

- [ ] Change https://flowtype.org/docs/third-party.html#_ to point to flow-typed instead of rolling your own declarations
- [ ] Split https://flowtype.org/docs/declarations.html#_ into separate pages for lib defs and `.js.flow` files, and clarify / distinguish what they are / should be used for

**Comment by GAntoine** [comment]
The README was updated with #1017, and now links to the new™ Wiki docs.
