### ISSUE TITLE
Express' Request and Response types don't work for middlewares or routes.

### ISSUE THREAD

**Issue by despairblue** [flowtype/flow-typed#274]
I'm trying to type express middlewares, but if I omit the type signature they end up being _any_:

``` js
/* @flow weak */

const express = require('express')
const router = new express.Router()

router.get('/', function (req, res) {
})
```

``` sh
$ flow type-at-pos router.js 6 28
any
/home/despairblue/git/wunderflats/api/router.js:6:27,6:29
```

And annotating them using the _Request_ and _Response_ classes from the express libdef leads to this:

``` js
/* @flow weak */

const express = require('express')
const router = new express.Router()

router.get('/', function (req /* : Request */, res /* : Response */) {
})
```

```
router.js:6
  6: router.get('/', function (req /* : Request */, res /* : Response */) {
     ^ call of method `get`
  6: router.get('/', function (req /* : Request */, res /* : Response */) {
     ^ call of method `get`. Function cannot be called on any member of intersection type
 92:     (middleware: Middleware): T;
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^ intersection. See lib: flow-typed/express_v4.x.x/flow_>=v0.25.x/express_v4.x.x.js:92
  Member 1:
   92:     (middleware: Middleware): T;
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^ function type. See lib: flow-typed/express_v4.x.x/flow_>=v0.25.x/express_v4.x.x.js:92
  Error:
    6: router.get('/', function (req /* : Request */, res /* : Response */) {
                  ^^^ string. This type is incompatible with
   92:     (middleware: Middleware): T;
                        ^^^^^^^^^^ union: function type(s). See lib: flow-typed/express_v4.x.x/flow_>=v0.25.x/express_v4.x.x.js:92
    Member 1:
     89:     ((req: Request, res: Response, next: NextFunction) => mixed) |
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ function type. See lib: flow-typed/express_v4.x.x/flow_>=v0.25.x/express_v4.x.x.js:89
    Error:
      6: router.get('/', function (req /* : Request */, res /* : Response */) {
                    ^^^ string. This type is incompatible with
     89:     ((req: Request, res: Response, next: NextFunction) => mixed) |
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ function type. See lib: flow-typed/express_v4.x.x/flow_>=v0.25.x/express_v4.x.x.js:89
    Member 2:
     90:     ((error: ?Error, req : Request, res: Response, next: NextFunction) => mixed);
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ function type. See lib: flow-typed/express_v4.x.x/flow_>=v0.25.x/express_v4.x.x.js:90
    Error:
      6: router.get('/', function (req /* : Request */, res /* : Response */) {
                    ^^^ string. This type is incompatible with
     90:     ((error: ?Error, req : Request, res: Response, next: NextFunction) => mixed);
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ function type. See lib: flow-typed/express_v4.x.x/flow_>=v0.25.x/express_v4.x.x.js:90
  Member 2:
   93:     (...middleware: Array<Middleware>): T;
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ function type. See lib: flow-typed/express_v4.x.x/flow_>=v0.25.x/express_v4.x.x.js:93
  Error:
    6: router.get('/', function (req /* : Request */, res /* : Response */) {
                  ^^^ string. This type is incompatible with
   93:     (...middleware: Array<Middleware>): T;
                                 ^^^^^^^^^^ union: function type(s). See lib: flow-typed/express_v4.x.x/flow_>=v0.25.x/express_v4.x.x.js:93
    Member 1:
     89:     ((req: Request, res: Response, next: NextFunction) => mixed) |
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ function type. See lib: flow-typed/express_v4.x.x/flow_>=v0.25.x/express_v4.x.x.js:89
    Error:
      6: router.get('/', function (req /* : Request */, res /* : Response */) {
                    ^^^ string. This type is incompatible with
     89:     ((req: Request, res: Response, next: NextFunction) => mixed) |
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ function type. See lib: flow-typed/express_v4.x.x/flow_>=v0.25.x/express_v4.x.x.js:89
    Member 2:
     90:     ((error: ?Error, req : Request, res: Response, next: NextFunction) => mixed);
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ function type. See lib: flow-typed/express_v4.x.x/flow_>=v0.25.x/express_v4.x.x.js:90
    Error:
      6: router.get('/', function (req /* : Request */, res /* : Response */) {
                    ^^^ string. This type is incompatible with
     90:     ((error: ?Error, req : Request, res: Response, next: NextFunction) => mixed);
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ function type. See lib: flow-typed/express_v4.x.x/flow_>=v0.25.x/express_v4.x.x.js:90
  Member 3:
   94:     (path: string|RegExp, ...middleware: Array<Middleware>): T;
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ function type. See lib: flow-typed/express_v4.x.x/flow_>=v0.25.x/express_v4.x.x.js:94
  Error:
    6: router.get('/', function (req /* : Request */, res /* : Response */) {
                       ^ function. This type is incompatible with
   94:     (path: string|RegExp, ...middleware: Array<Middleware>): T;
                                                      ^^^^^^^^^^ union: function type(s). See lib: flow-typed/express_v4.x.x/flow_>=v0.25.x/express_v4.x.x.js:94
    Member 1:
     89:     ((req: Request, res: Response, next: NextFunction) => mixed) |
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ function type. See lib: flow-typed/express_v4.x.x/flow_>=v0.25.x/express_v4.x.x.js:89
    Error:
     89:     ((req: Request, res: Response, next: NextFunction) => mixed) |
                    ^^^^^^^ Request. This type is incompatible with. See lib: flow-typed/express_v4.x.x/flow_>=v0.25.x/express_v4.x.x.js:89
      6: router.get('/', function (req /* : Request */, res /* : Response */) {
                                            ^^^^^^^ Request
    Member 2:
     90:     ((error: ?Error, req : Request, res: Response, next: NextFunction) => mixed);
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ function type. See lib: flow-typed/express_v4.x.x/flow_>=v0.25.x/express_v4.x.x.js:90
    Error:
      6: router.get('/', function (req /* : Request */, res /* : Response */) {
                                            ^^^^^^^ Request. This type is incompatible with
     90:     ((error: ?Error, req : Request, res: Response, next: NextFunction) => mixed);
                       ^^^^^ null. See lib: flow-typed/express_v4.x.x/flow_>=v0.25.x/express_v4.x.x.js:90
```
## Versions:
- **flow**: 0.30.0

**Comment by ctrlplusb** [comment]
I normally import the types rather than the classes.
 
```typescript
import type { $Request, $Response } from 'express';

const middleware = (req : $Request, resp : $Response ) => undefined;
```

Not sure how type importing works without es6 modules.  I'll take a guess and say that you could maybe use the `typeof` technique?

```typescript
const $Request = typeof Request;
...
```

**Comment by ctrlplusb** [comment]
Hmmm, [docs](https://flowtype.org/docs/modules.html#import-type) don't allude to any difference between type imports on a commonjs/es6 modules project.  Maybe the `import type...` will work for you.

**Comment by vaukalak** [comment]
@ctrlplusb I'm using the same approach with flowtype 0.32, but get following error:

```
3: import type { $Request, $Response, Middleware } from 'express';
                   ^^^^^^^^ Named import from module `express`. This module has no named export called `$Request`.
```

**Comment by ryyppy** [comment]
The express module does a `declare module.exports: ...`, that means all `declare` statements before that are hidden in the `declare module` scope... the libdef needs to explicitly export that in the `module.exports` statement.

**Comment by thejameskyle** [comment]
I have a different set of issues when I try it out that come down to the definition of [`Middleware`](https://github.com/flowtype/flow-typed/blob/master/definitions/npm/express_v4.x.x/flow_%3E%3Dv0.25.x/express_v4.x.x.js#L90-L92)

It seems that it's using a union type (`A | B`) instead of an intersection type (`A & B`).

However I don't know where in the express api you have [this](https://github.com/flowtype/flow-typed/blob/master/definitions/npm/express_v4.x.x/flow_%3E%3Dv0.25.x/express_v4.x.x.js#L92).

Changing the definition of Middleware to the following seems to fix everything:

```js
declare type Middleware = ((req: Request, res: Response, next: NextFunction) => mixed);
```

[[try](https://flowtype.org/try/#0PQKgBAAgZgNg9gdzCYAoVBLAtgBzgJwBcxCBPHAUzAG8wBlC-AN0bAF8wp84swByABaFCOPgG50AEwoBjGAEN8VMpTAAlOAFdCjAPI5CGOADsAzmAC8NVGDAz5pigzMZDLAPwAuMACM4cGAp5YwAaGzAsRgBzCgAFRXksUy9ff0DgsNtTQnwMGUIUvwCg41Q2CVRpOUUqatNzNQoAR00KbMbTPDMKACEHKmpw+RwcbwBBEZg8+UMTCVsYwgAKKAwKGElvbNzjKIBKLZyMXbAAHzAmOAxJCTYpWQUlOwV69WbW7LAKAA8dY0lzEIRAASACSxhkPGOUQAsm1TPIYhEMN9jg13m1CB0uo4+o5rLYfP0AKr4GCHHZReapSSkbxYFEUG7hSFwADWa1M3moAG1WRyKBToQBdIW7crhLhtATeIrpYzUgRwbLGRKC1LFYLUjCjMDbaHanBcsBjfD4eSkAA8+t2AD5qZFCErNnqjrtqQQMFFjvIYKTya7KdScAkktyeSHzVgxVFRYHoRLbCGnTHg9xCHBIQHBMIjXwzvwgaJqS1GHSaDzVZEY3GbVFE2BuNp1XXqY4ZJolLK0iU217jEyAML+AXG3mmftDkdrGsxhvZX3quW98KmTQ+SQ8eRo8Zmi3Wt1Re3hb4CfDdzUKoYyGQUAymJYqNoxg7xk7nKC+xzU+Q3u+EUxBwERRHAApYADpIJkYD8FA41TXNK061tV86wLT8YG-a9b3vABRCE4EkaEH0g8CKAIojdl3RCD0pFCY3Qr8KB-P97wAGWCKJNERNoIMghQqJNPckMPei3yiRjMOY8IBCCaR8BWNYNhfBjzkua5tQfJ8VI1eVg1DJYqxbQ8QjAaRP00GBCAANV9VoUjrVDDwLdTmTuSoHhqEhyCoYd2TWfRZjMSwCTMrdjgckzwnIyFpBSJYmDs4zKT2SxbXEzIvm+HAMCUZJvAAERmChMqLXRjBgUhCh7DJwiweRvjGGJIspTLkwEFroUy9tOwoarL26ydJH6+UygqKpHmUHy3n+RhB19GAiRkNkQqWRhzzAXCzQIAtjEsmBTKELAYE63ZUosdKGW+Jlxs8p4n3ocjJAAMQwQJAqMYKrEGWx6sa5rvD2rAfEYTLuDgAoY0yl5CBhQiMFWJkRpKUq5MYfKKyM2dxLYTLN0IVZAgxvgFsQfNzj4aRjFIcn+H7AgKD4Mb7mqJ46nRToTHxH4-gBMAi2BQcpnIrEMU+K60TeUt2jaHFen6ULZPkeTTGcQgLz08J4HsTDwyx8S4yupkG2GSh-kU9YXTrUzEpgeydKdDBTB-YRfwESJjGWQnyLVU79m8R3nZZacKEMtUoYuJKI7gAxPoxvyBQ+rnX0D6k5CCfAE7WMPqwysAY6C+OQ6TswU4EJ3qU3BAKrgZWlnaiPvaMv3TJ1xbfzZeL1pSdwtu4fBzvS1yy4ryUCHq5Yn1MXQfAAK1kdWK20g3vGezQISCtgR6D2xZ9MEwlj8WkUiNyRt+pPeTBwQ-CKq+lGTPgPy53sApmMNkHzfj+9fDlecfPrWmYZifXrjMGU4kAG2CUERJQ+QlidgDNbMApFFBRHgsJS0rkxKp3CNA3KC8lgLkIJoY0QMQb4FMggiOKD8BoOovuLBkDGxPUYAlNYCAI7ay-CfB+rcFpLTZN4Ros1M78I7kwxw5sj532RNdR+JBn5tieq9QIoCUx5wLnHFIzgXpvQoCXUwfCYDt2Wl3M0Pc+4EEHrIpkEinp0EIDMEhhDHHEMAoRdUZDGB2K9kpK2JlI52z6g7RRq5XHOKISQ4c0hAaaGBt4p+o9bBPkfD5EJSTI74FIBbZSEDElB3chNLyD1gTYi5lQKwZTugSCKfdaapSxbEEqY0mpd0pqqAAHI8zXhvT6q1u7eF7ttAeaUbHMlqe0qgMJriSECAgLyVglhLCUE0IRjTTJ5TWZzbopkBy-G8F034PT8ifWsafPYt1WZUGODofAn5bzqC0DoOETpCIABUfKWjeelH6YAlgMkkLMig8yuxgGmYCuZNRXxvOpHxcCAKgUgvVAhfc4LEU1DEjC8IajwF1lOI0KIuFsqnDrDyYUplSIIshaClFVo0XUooJi24LNJpgBuYwe5VANDNnwC850HzKBfJ+diqlwKajeHpWKpQ0LYWUpmQy+hdL5VSsZTK7FDdxL4ooIS4lpLyXIMgqKpFirLSSqRUy9VYCI5NluUIp5CSwBYsKW054DgGj2tCosO1zY+XvM+YHY8SZlSL25c8igrzJACooJaANwZtDerDRGqNMbn6Bv5nJBNFBfWRv9amyu6xw3qlDVm8N-Lc1OzTZormmbs3JtjeEHIv4i32treW0wabIQ4HLMW1tgr622G1oIx5PrS1+r7XmuqbIsw1tHTm8dFaHRwBYDOpNba004E7DEFdZb53trTDHVY-xt1jujf2sAOBuAjBmNBY9c7T0TtsOvQdt660PuYXgIgL610OjZL+Nwrhu0ttna+hdLJZLLSeV+3dabIi0ObSO1d0GKi2GAMASAbzdAFV0GCp2E4Th8CwAAWkcIoaC+YfDaDAIsTg8AkBvUCFEX0YAjJfGGeBdAthjAQwRoBhDO772gayOuUwMhcggygwJvd4R15rh8CJsT8HE38ZTYJ8917wE9uA9+1cGcb3DqUyelTUnbCQmMAOfIEmjPHmdVc11rxi34Cyrzd1zZQqme2JofIBAlhVrMCkBzBjXyuWpCQxTjBe2SbTTa0OGrHKZrbK4vIfzXwOeZR5WzUB14nJMHqRgLAHHAJkMs-wi8kG+YxjPee+RXxmpqJc1l7MTSTGmEFJzT0XO3NkZLCgLBPamGBLhXrhBcIMmEKwX57mcieYzApILVxmQDqAbrTGv86yGwfg2LAWhPaxcPNSKY2RyL1wIIvLxFD+bBubhHAR8AogpDO0YkxndvBrXMYMyxIyLpjNfAwZgjB9tOz+Mdz9zG4nkMOpd32Ec24CLMfgCxwyzkPx+3l-7WtAdHY-adsHoM7BiNMS9gZYAhn9yR3IlHf38AA8O8YHF0P8fPb+UTknVjRnnO8L9lgVP0c06WMBf4gRvCVYXo92HhO3vE4+2T2xHPUfc9sERBEPhVH6zixceblcnbyGV0yHOyVoSvmXFqaKqodd650sFk32vAiSHN3k3SK5bDkW9AOO3SCYcd1XlloKc2NLhFACAcIyAcNyLAAgejzGIa+GUPINk5EwAOAT4E1o+dY4mHAmAUE9QU+KG25IMAJDoQKKoAAcVwm8-muYIizuY2qBP-xi9UfDZwHaoFDC7FMOx2wyA0AobQwscNbvDyvlPko5YquAm21aPfcnM+bq4JYQpCfrVU+F10PgY5QUf65zW3PyQuM8fGIEWskR80j-iO8JbmzrKSkTBwFMewrWrB34f8AuYLKvKJUcz8C98JuTYtfBfxa0+lMlQ0zygDAFIC0BICyRIDgEPxgFfgwDjyT0y16RMFMlcDDwj1CwUSdj1H7CcSUDCUKy2FRwK0MBkFALQwAAMiE8gaDz1L1GAyB85jBG80DstShbAHMA4fI4AICHNqCwAaCHNGCL0Y4WDSA2CODvdPpmZbBwh0BJtGx7VHMrABwkAf88pO8HMlg9h0Bot8BwJFglg+BgA+BTJODWtllmgNk2hUpflbCmhwIiRHB-RYl4kB5bgLklDFDFCgA)]

**Comment by gcedo** [comment]
@thejameskyle Thanks, that worked for me 😊

**Comment by shuhei** [comment]
Without changing the libdef, the following is working for me on flow 0.38.0:

```js
router.get('/', function (req: express$Request, res) {
})
```

or

```js
import type { $Request } from 'express';

router.get('/', function (req: $Request, res) {
})
```
