### ISSUE TITLE
Remove the definition for enzyme@2.x.x? Or a way to specify which libdef to use when there are multiple?

### ISSUE THREAD

**Issue by cdchambers** [flowtype/flow-typed#322]
There are two enzyme definitions right now, 2.x.x and 2.3.x. The latter is a superset of the former. 

When installing through the flow-typed cli, any version that matches 2.3.x will also match 2.x.x and the cli installs 2.x.x by default.

Is there a way for me to force flow-typed to install 2.3.x? The version number approach doesn't appear to cut it...

**Comment by wbeard** [comment]
I ran into this too. It looks like `filterLibDefs`'s sorting in `lib/libDefs` may not be correct? It ends up returning a list of libdefs by version in ascending order, rather than by descending. If it were descending, it'd indicate a more exact match.

Maybe one of the maintainers could help us understand why it works this way?

**Comment by jeffmo** [comment]
@palange is knee-deep in this code right now over in https://github.com/flowtype/flow-typed/pull/289

**Comment by palange** [comment]
#289 is merged, but didn't address this issue.

**Comment by jeffmo** [comment]
FWYI: I just chatted with @palange about this and here's the updated plan to address this:

Have `flow-typed install` find the *lowest* satisfying version of the range specified on the CLI/package.json, then find the *highest* satisfying libdef version in flow-typed to install (and assume an implicit `^` in front of all libdef versions in flow-typed).

So to prove we're sane here, lets run through a few examples to test this procedure:
Assume we have 2 libdefs: One for 2.x.x and one for 2.3.x:

**If a project states that it uses `2.1.x`**

1. `2.1.0` is the lowest-satisfying version of `2.1.x`
1. Between `2.x.x` and `2.3.x`, `^2.x.x` is the *highest* satisfying libdef -- and so it will be installed

**If a project states that it uses `2.3.x`**

1. `2.3.0` is the lowest-satisfying version of `2.3.x`
1. Between `2.x.x` and `2.3.x`, `^2.3.x` is the *highest* satisfying libdef -- and so it will be installed

**If a project states that it uses `2.7.x`**

1. `2.7.0` is the lowest-satisfying version of `2.7.x`
1. Between `2.x.x` and `2.3.x`, `^2.3.x` is the *highest* satisfying libdef (it does satisfy since `3` is a minor version and we don't have anything closer to `7` to install) -- and so it will be installed.

---

In all cases, if we can't find a libdef that matches exactly (ignoring patch version) then the `flow-typed install` CLI should emit a warning letting the user know there may be some semantic APIs not include in the libdef that was installed for them (at which point they may choose to go create a libdef for their specific version, or perhaps the less-complete libdef is still satisfactory to them).

cc @palange for spot-checking my summary

**Comment by palange** [comment]
The summary looks good. And I'll take on this task...

**Comment by palange** [comment]
PR #326 should address this issue by choosing the definitions for enzyme 2.3.x if you specify an enzyme dependency of 2.3.0 or greater. The dependency can be specified via npm, in package.json, or on the command line: `flow-typed install enzyme@2.3.0`. You may need to use overwrite to install over the existing version.
Thanks for reporting the issue!
