### ISSUE TITLE
[feature request] Allow argument to specify install location

### ISSUE THREAD

**Issue by ctrlplusb** [flowtype/flow-typed#337]
I personally prefer to keep the root of my projects as clean as possible, and group my tooling etc into a subfolder.

**Comment by jeffmo** [comment]
I think this is pretty reasonable, although thinking through caveats:

This would mean that you'd need to specify the same directory each time you run any `flow-typed` commands (if you use a non-standard directory). If you (or a contributor of yours) forgot to do so, the behavior could get a little messy (installing into the wrong directory, searching for existing libdefs to check for updates in the wrong place, etc).

A standard solution to this would be to add support for a `.flowtypedrc`...but I'm very hesitant to add configuration these days (nobody wins when you add config :p ).

**Comment by jeffmo** [comment]
Hmmm... What if we changed the default name of the directory to `.flow-typed` (dot-hidden)?

Presumably you already have `.flowconfig` (and probably other dot-prefixed stuff) in the root dir, so maybe that's a reasonable option?

**Comment by ctrlplusb** [comment]
It feels like a good middle ground. :)

**Comment by jeffmo** [comment]
Ok, I spoke to the team and a few others and there were some concerns raised about complicating the lookup process for the default `flow-typed` directory. Specifically: We want tooling to be able to find this directory easily so that it can be inspected and do things like inform you when there's a new libdef you didn't previously have, inform you when there's an update to one you already have installed, de-duplicate definitions, and any other management tasks that we intend to automate over time.

So after sleeping on this I'm convinced that `.flow-typed` might have been a better name if we were introducing it today, but since it's out there and people are already using `/flow-typed` it's probably not worth the thrash to change the name.

Thanks for the report and please keep the feedback coming! :)

**Comment by jeffmo** [comment]
I should toss in that you could also write your own `npm script` along the lines of:

`mv tools/flow-typed . && flow-typed install && mv flow-typed tools/`

And you'd need to add `tools/flow-typed` to the `[libs]` section of your `.flowconfig`.

This would opt you out of the aforementioned benefits from future-tooling, but it's possible if you really need that directory structure.

**Comment by ctrlplusb** [comment]
Fair enough. :)

Thanks for the detailed explanation, friendly tone, and tip!
