### ISSUE TITLE
Support Angular 1.x

### ISSUE THREAD

**Issue by csvan** [flowtype/flow-typed#361]
There is some previous work on this available: https://github.com/uberstudio/angular-flowtype

Even if Angular 1.x is technically on the way to becoming obsolete, it still enjoys wide community support and would probably be a good framework to support.

**Comment by djleonskennedy** [comment]
+

**Comment by AndriiDidkivsky** [comment]
+

**Comment by sergiy-zvyahelskiy** [comment]
+

**Comment by noppa** [comment]
+1

https://github.com/uberstudio/angular-flowtype isn't related to this project, is it? It seems to be angular wrapper for [flowtype](https://github.com/jkroso/flowtype), a font-size library.
Maybe something like https://github.com/solnet-aquarium/flow-interfaces-angular is more useful for flow-typed.

There are just way too many things called _Flow_... :smile:

**Comment by marudor** [comment]
Yes. https://github.com/uberstudio/angular-flowtype has nothing to do with flow.
https://github.com/solnet-aquarium/flow-interfaces-angular does.

If someone wants to work on this feel free to send a PR.

**Comment by LoganBarnett** [comment]
I've been putting this off for a while, so instead of putting it off further I'm going to share what I have:

I have some progress done on Angular 1.x defs. I'd started on this before I saw the post about @solnet-aquarium's repository. Among other things, I need to pull those in or otherwise coordinate on that effort.

I'm in the middle of privatizing the internal type defs and figuring out how to run the def tests for just angular. It also has some tests in the works. I don't know if my refactors have broke anything just yet.

You can get to the repo here: https://github.com/LoganBarnett/flow-typed/tree/angular-1.x

Also if someone could clue me in as to how to express Angular's dependency injection, that would be swell. The gist is it is a list with a series of strings, and then a function as the very last element. Generally the strings correspond with the function's parameter names. I'd be pretty happy with just enforcing some variable number of strings and a function of any kind. So far I just have `Array<string | Function>`.

**Comment by GAntoine** [comment]
Closing since definitions were added in #785.
