### ISSUE TITLE
Commands for developing flow-typed defs leak to end users

### ISSUE THREAD

**Issue by nmote** [flowtype/flow-typed#403]
`flow-typed run-tests` and `flow-typed validate-defs` both seem to pertain only to working on this repository. However, they are both available when you install flow-typed as an end user.

They error with:

```
Running definition tests in /usr/local/lib/node_modules/definitions/npm...

UNCAUGHT ERROR: Error: ENOENT: no such file or directory, scandir '/usr/local/lib/node_modules/definitions/npm'
    at Error (native)
```

and

```
UNCAUGHT ERROR: Error: ENOENT: no such file or directory, open '/usr/local/lib/node_modules/definitions/.cli-metadata.json'
    at Error (native)
```

respectively.

These commands should not be available to end users.

**Comment by jeffmo** [comment]
Fair enough -- it might make sense to split these up somehow. It's definitely true that the majority case is that they aren't useful for libdef consumers right now.

The original reasons I put them together is because (a) it was just simpler and (b) it meant that once you have the CLI installed, you can easily also run tests on your own checkout of the github repo (which you may be working within to update a libdef, for example).

There's probably no harm in just turning these into non-CLI scripts that are part of the repo, though...

Perhaps a really easy short-term way to indicate that "these commands are not like the other" would be to just prefix them all with `repo-`?

**Comment by relekang** [comment]
> Perhaps a really easy short-term way to indicate that "these commands are not like the other" would be to just prefix them all with repo-?

What about changing the help text of the command to say that it only works in a flow-typed clone? and maybe also create some error messages that explains why it does not work?

**Comment by jeffmo** [comment]
@relekang: Yea that's a good idea as well.

**Comment by jeffmo** [comment]
Anyone wanna send a PR? I'm going to be on a limited-connection roughly until mid-next-week

**Comment by relekang** [comment]
@jeffmo Yeah, I'll try to get one up today.
