### ISSUE TITLE
How to write a libdef for a function that has another function as a property?

### ISSUE THREAD

**Issue by callumlocke** [flowtype/flow-typed#851]
The [resolve-from](https://github.com/sindresorhus/resolve-from) module's API looks like this:

```js
const resolveFrom = require('resolve-from');

resolveFrom('foo', './bar'); // returns a string (or throws an error)
resolveFrom.silent('foo', './bar'); // returns a string or null
```

What is the proper way to declare that in a libdef? I tried the following:

```js
declare module 'resolve-from' {
  declare module.exports: (
    | ((fromDir: string, moduleId: string) => string)
    | { silent: (fromDir: string, moduleId: string) => (string | null) }
  );
}
```

...and it seems to work OK when calling `resolveFrom.silent(...)`, but it fails when calling `resolveFrom(...)` with "Callable signature not found in object type"

**Comment by swansontec** [comment]
I believe the correct solution is to use `&` instead of `|`, since it must be *both* callable and have the `silent` property:

```js
declare module 'resolve-from' {
  declare module.exports: ((fromDir: string, moduleId: string) => string) & {
    silent: (fromDir: string, moduleId: string) => string | null
  }
}
```

This makes the `resolveFrom` function callable, and `resolveFrom.silent` is callable as well, but Flow isn't checking the parameters for `silent`. It treats `silent` as any. I believe this is a bug, and should be reported in its own issue if anybody can double-check it.
