### ISSUE TITLE
flow-typed broken by recent PR

### ISSUE THREAD

**Issue by steida** [flowtype/flow-typed#881]
https://github.com/flowtype/flow-typed/pull/785#issuecomment-304462772

**Comment by JamieDixon** [comment]
We're also seeing this issue however we have no angular dependencies.

**Comment by JamieDixon** [comment]
Based on the error message provided in the comment, it seems like the issue might be here:

https://github.com/flowtype/flow-typed/blob/d975648089169d519666b628ea201ea7c9bec2c2/cli/src/lib/flowVersion.js#L398

`or 'flow_v-v' (for a range).`

But here we're seeing a space used instead of a `-` to separate the versions.

**Comment by kernwig** [comment]
First, this is being pulled in even though we use Angular v1.6.4, so I might expect problems just from that. However, flow is complaining about long-existing functions like angular.isUndefined() and angular.isDefined(). Also, some controller declarations also fail.

**Comment by dreid** [comment]
This should be fixed in v2.2 by #1311
